language: minimal
dist: xenial

env:
  - ID=fr.natron.Natron
  - ID=org.gnome.gedit
  global:
    - DISPLAY=:99

matrix:
  include:
    - name: "Build for x86_64"
      env: ARCH=x86_64

before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt-get -y install flatpak xvfb x11-xserver-utils imagemagick
  - wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)

script:
  - Xvfb :99 -screen 0 800x600x24 >/dev/null 2>&1 &
  - chmod +x *
  - ./build-gedit.sh

after_script:
  - killall Xvfb

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
