language: minimal
dist: xenial

env:
  global:
    - DISPLAY=:99

matrix:
  include:
    - name: "Build for x86_64"
      env: ARCH=x86_64

before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt-get -y install flatpak xvfb x11-xserver-utils imagemagick

install:
  - sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - sudo flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

script:
  - Xvfb :99 -screen 0 800x600x24 >/dev/null 2>&1 &
  - chmod +x ./flatpak2appdir
  - chmod +x ./build-gedit.sh
  - ./build-gedit.sh


after_script:
  - killall Xvfb

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
